// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqkdishkffvlzhhqoecd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtxa2Rpc2hrZmZ2bHpoaHFvZWNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxOTczNjMsImV4cCI6MjA2Nzc3MzM2M30.Ii4IIdcITdkI-kNVYyWDkMHuXdWlu_mPfaboPcX0Mno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});